#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-golang-glog
Version  : 23def4e6c14b4da8ac2ed8007337bc5eb5007998
Release  : 5
URL      : https://github.com/golang/glog/archive/23def4e6c14b4da8ac2ed8007337bc5eb5007998.tar.gz
Source0  : https://github.com/golang/glog/archive/23def4e6c14b4da8ac2ed8007337bc5eb5007998.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : go

%description
glog
====
Leveled execution logs for Go.
This is an efficient pure Go implementation of leveled logs in the
manner of the open source C++ package
https://github.com/google/glog

%prep
%setup -q -n glog-23def4e6c14b4da8ac2ed8007337bc5eb5007998

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/golang/glog"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x github.com/golang/glog

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/golang/glog/glog.go
/usr/lib/golang/src/github.com/golang/glog/glog_file.go
/usr/lib/golang/src/github.com/golang/glog/glog_test.go
